[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.0",
    "openai>=1.77.0",
    "requests>=2.32.3",
    "stem>=1.8.2",
    "trafilatura>=2.0.0",
]
